version: '3'
services:
  alf:
    image: gableroux/unity3d:2019.4.0f1
    volumes:
    - .:/VContainer
    working_dir: /VContainer/tmp
    command: /opt/Unity/Editor/Unity -quit -batchmode -nographics -logFile -createManualActivationFile
  test:
    image: gableroux/unity3d:2019.4.0f1
    volumes:
    - .:/VContainer
    working_dir: /VContainer
    command: >
      /bin/sh -c "
        /opt/Unity/Editor/Unity -quit -batchmode -nographics -silent-crashes -logFile -manualLicenseFile ./tmp/Unity_v2019.4.0f1.ulf ||
        /opt/Unity/Editor/Unity -runTests -batchmode -nographics -silent-crashes -logFile -projectPath ./VContainer -testResults ./tmp/TestResults.xml -testPlatform StandaloneLinux64 -scriptbackend=mono
      "
  performance-test:
    image: gableroux/unity3d:2019.4.0f1
    volumes:
    - .:/VContainer
    working_dir: /VContainer
    command: >
      /bin/sh -c "
        /opt/Unity/Editor/Unity -quit -batchmode -nographics -silent-crashes -logFile -manualLicenseFile ./tmp/Unity_v2019.4.0f1.ulf ||
        /opt/Unity/Editor/Unity -runTests -batchmode -nographics -projectPath ./VContainer.Benchmark -testResults tmp/PerformanceTestResults.xml -testPlatform StandaloneLinux64 -scriptbackend=mono
      "
